### ISSUE TITLE
The latest version v2.0.7b keep crashing because of timeout

### ISSUE THREAD

**Issue by h4rdkor1** [KryptoST/SRTranslatorGUI#18]
The latest version keep crashing while translation and the api version doesnt even start even after having pro api key.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
SrtTranslatorAPI.Translator.TimeOutException: Translation timed out
   at SrtTranslatorAPI.Translator.deeplsrap.Translate(String text, String sourceLanguage, String destinationLanguage) in C:\Users\omen\source\repos\SrtTranslatorAPI\SrtTranslatorAPI\Translator\deeplscrap.cs:line 159
   at SrtTranslatorAPI.Translator.srtfile.Translate(Translator translator, String sourceLanguage, String destinationLanguage, Int32& progre) in C:\Users\omen\source\repos\SrtTranslatorAPI\SrtTranslatorAPI\srtfile.cs:line 130
   at SRTranslatorGUI.Form1.<>c__DisplayClass32_0.<traducirAsync>b__0() in C:\Users\omen\source\repos\SRTranslatorBeta\SRTranslatorBeta\Form1.cs:line 524
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SRTranslatorGUI.Form1.<traducirAsync>d__32.MoveNext() in C:\Users\omen\source\repos\SRTranslatorBeta\SRTranslatorBeta\Form1.cs:line 507
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SRTranslatorGUI.Form1.<translatesrtfiles>d__21.MoveNext() in C:\Users\omen\source\repos\SRTranslatorBeta\SRTranslatorBeta\Form1.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
![Screenshot 2024-01-11 000657](https://github.com/KryptoST/SRTranslatorGUI/assets/21197676/1d03f3cb-00eb-4d61-a007-e8b961f03a51)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SRTranslatorBeta
    Assembly Version: 2.0.7.0
    Win32 Version: 2.0.7.0
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/SRTranslatorBeta.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9191.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.4.0
    Win32 Version: 1.1.4.0
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.4.0
    Win32 Version: 1.1.4.0
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
FreeProxy
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/FreeProxy.DLL
----------------------------------------
WebDriver
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/WebDriver.DLL
----------------------------------------
SrtTranslatorAPI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/SrtTranslatorAPI.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.11.46.0
    Win32 Version: 1.11.46
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/HtmlAgilityPack.DLL
----------------------------------------
SeleniumExtras.WaitHelpers
    Assembly Version: 3.11.0.0
    Win32 Version: 3.11.0.0
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/SeleniumExtras.WaitHelpers.DLL
----------------------------------------
SRT
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/desig/OneDrive/Desktop/SRTranslator.v2.0.7b/SRT.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`
![image](https://github.com/KryptoST/SRTranslatorGUI/assets/21197676/426d63b7-978c-4b0f-b1bf-197a281fe8ce)

**Comment by pise77** [comment]
me toooooooooo

**Comment by ghost** [comment]
I have the same issue.

**Comment by XZTence** [comment]
I have the same issue too
